# Economy of agglomeration on Business Clusters

## Applied Data Science Capstone by IBM/Coursera

## Table of contents
* [Introduction and Purpose](#introduction)
* [Methodology](#methodology)
* [Data](#data)
* [Analysis](#analysis)
* [Results](#results)
* [Conclusion](#conclusion)

## Introduction and Purpose <a name="introduction"></a>

All-round the world companies and small businesses are agglomerated in one district or around. This agglomeration contributes significatively to decreasing the price of production, deployment, as it does on creating a more innovative and productive environment for their employees. Many of these effects are widely known on business clusters and lately have shown amazing results on other sectors such as biotech, high-tech, and so on, having a great example on BioPharma clusters in Switzerland or HighTech ecosystems in other countries. 

The success of a company is not determined by the location of the office although it can affect directly, as clusters pretend to do. Knowing that this project is a beginner-intermediate one and the subject chosen is complex if it is studied in complete detail, the results will be shown as probable, without determining the rest of the factors that can affect the success in the location of your company or your services around a particular location. As the capstone project demands it will be using Foursquare API that we will get the data to find relations. 

The purpose of this project is to give possible solutions, in the location of the company, for these expecting to grow fast in a short time, in the same way, contribute to the proper location of services and franchises when you want them located in these clusters. 

I encourage anyone with knowledge and interest in this field to use my work and find out more about the relationship between business, biopharma, or startup clusters and their location and services around the same. I think that these models can be of remarkable interest for all the countries that are developing their clusters to do it successfully, particularly now, that we live a pharmaceutical revolution due to the current situation with Covid-19.

## Methodology <a name="methodology"></a>

The stages from acquisition to deploy a solution have been the next:

- Acquisition of Data trough Deloitte's PDF EMEA Fast Growth 2019 and the consequent cleaning.
- Location of the address, latitude and longitude of the companies listes using GeoCode API of Google.
- Mapping using floium the companies by the industry sector and cluster them with k-means.
- Identify services around companies by sector using Foursquare API.
- Analysing and visualizing the results.

In [7]:
import numpy as np
import sys
import geopy
import seaborn as sns
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import csv
import pylab as pl
import urllib.parse
import folium
import json
import geojson
import requests
import matplotlib.cm as cm
import matplotlib.colors as colors

In [8]:
from folium.folium import Map
from sklearn.cluster import AgglomerativeClustering
from geopy.geocoders import Nominatim, GoogleV3      # convert an address into latitude and longitude values
from pandas.io.json import json_normalize            # tranform JSON file into a pandas dataframe
from sklearn.cluster import KMeans

%matplotlib inline

## Data <a name="data"></a>

### Acquisition of Data

In [18]:
df = pd.read_csv("C:/Users/marc/Desktop/Notebook/gx-emea_fast_500_Ranking-2019.csv")
df.dropna(how='any', inplace = True)
df.drop(df.index[[25, 51, 77, 103, 129, 155, 181, 206, 230, 256, 282, 308, 334, 359, 384, 409, 435, 461, 486]], inplace = True)
df['Growth'] = df['Growth'].apply(lambda x: int(x.split("%")[0].replace(' ', '')))
df.rename(columns={'Growth': 'Growth %', 'Company name for communication': 'Company', 'Industry sector': 'Sector'})
df1 = df  #Saving the original DataFrame for other uses
df
# At this stage the dataframe has been cleaned of NaN's and other unuseful values

,Ranking,Company name for communication,Country,Growth,Industry sector
0,1,Revolut,UK,39754,Fintech
1,2,OakNorth,UK,30706,Fintech
2,3,Cloud&Heat Technologies GmbH,DE,21474,Environmental Technology
3,4,DivideBuy,UK,19572,Fintech
4,5,FINEWAY,DE,16594,Software
...,...,...,...,...,...
571,496,shopware AG,DE,159,Software
572,497,metacrew group GmbH,DE,159,Media and Entertainment
573,498,LESCAV,Belgium,158,Hardware
574,499,Paysera LT,Lithuania,158,Fintech
575,500,Arcus Global,UK,157,Software

### UK DataFrame

In [21]:
#Code to inspect the data by sector and countries
df['Industry sector'].value_counts()
df['Country'].value_counts()

# I will choose UK as it is de country with more companies for the first analysis
df = df[df['Country'] == 'UK'] 
# I will work with these companies which are more than five in the same sector
df = df[df['Industry sector'] != 'Environmental Technology'] 
df = df[df['Industry sector'] != 'Communications']
df = df[df['Industry sector'] != 'Healthcare and Life Sciences']

df.head(15)

,Ranking,Company name for communication,Country,Growth,Industry sector
0,1,Revolut,UK,39754,Fintech
1,2,OakNorth,UK,30706,Fintech
3,4,DivideBuy,UK,19572,Fintech
11,12,Moteefe,UK,7394,Media and Entertainment
20,21,Clearmatics,UK,4900,Software
29,26,ClearScore,UK,4382,Fintech
33,30,Lendable,UK,3883,Fintech
43,40,Privitar,UK,2797,Software
49,46,Onfido,UK,2324,Fintech
63,56,Paddle,UK,2013,Software
65,58,Darktrace,UK,1989,Software
66,59,Streetbees,UK,1984,Software
72,65,Iceotope Technologies Limited,UK,1895,Hardware
93,82,Yoyo,UK,1707,Fintech
95,84,Hostmaker,UK,1592,Software

### Netherlands DataFrame

In [22]:
# Using the original DataFrame we see NL as the second country with more companies on the list
df1['Country'].value_counts()
df1 = df1[df1['Country'] == 'NL']
# We will work with companyes with at least five times on the sector in the NL
df1['Industry sector'].value_counts()
df1 = df1[df1['Industry sector'] != 'Communications']
df1 = df1[df1['Industry sector'] != 'Healthcare and Life Sciences']
df1 = df1[df1['Industry sector'] != 'Fintech']
df1 = df1[df1['Industry sector'] != 'Hardware']
df1.head(20)

,Ranking,Company name for communication,Country,Growth,Industry sector
9,10,Flightgift / Hotelgift,NL,7628,Software
16,17,Mews Systems,NL,5384,Software
21,22,PastBook,NL,4623,Media and Entertainment
39,36,Simplicate,NL,3013,Software
81,74,Channable,NL,1791,Software
104,93,Scrambled Group,NL,1458,Media and Entertainment
117,102,Appwiki,NL,1281,Media and Entertainment
122,107,3D Hubs,NL,1258,Software
126,111,Parkos,NL,1234,Software
134,119,POSTEX,NL,1164,Software
135,120,Team Nijhuis,NL,1156,Media and Entertainment
139,124,APOC Aviation,NL,1088,Software
155,136,The Inner Circle,NL,963,Media and Entertainment
178,155,Zelfstroom,NL,895,Environmental Technology
187,164,SendCloud,NL,856,Environmental Technology
211,184,Cloud++,NL,769,Software
213,186,Studytube,NL,755,Software
253,222,Stars and Stories,NL,654,Media and Entertainment
270,235,Mapiq,NL,597,Software
272,237,SecureLink,NL,588,Software

### Geolocation of UK Companies

In [25]:
#Set instructions to use Google API
base_url= "https://maps.googleapis.com/maps/api/geocode/json?"
AUTH_KEY = "AIzaSyAkvUUxfKc4Z5uMv58wOsd2usIdDHvxQTk"
geolocator = GoogleV3(api_key = AUTH_KEY)

components = [ ('country', 'GB' )]
def get_location(x):
    return geolocator.geocode(x, components=components)

df["loc"] = df["Company name for communication"].apply(get_location)
df["point"]= df["loc"].apply(lambda loc: tuple(loc.point) if loc else None)
df[['lat', 'lon', 'altitude']] = pd.DataFrame(df['point'].to_list(), index=df.index)
## Adding manually the information that has not been reached by the API
df.loc[43,'loc'] = '(15 Hatfields, South Bank, London SE1 8DJ, United Kingdom)'
df.loc[43,'point'] = '(51.506855, -0.107148)'
df.loc[43,'lat'] = 51.50685
df.loc[43,'lon'] = -0.10714
df.loc[43,'altitude'] = '0'
df.loc[72,'loc'] = '(Brunel Way, Catcliffe, Rotherham S60 5WG, United Kingdom)'
df.loc[72,'point'] = '(53.386183, -1.378254)'
df.loc[72,'lat'] = 53.38618
df.loc[72,'lon'] = -1.378254
df.loc[72,'altitude'] = '0'
df.loc[121,'loc'] = '(175 Glasgow Rd, Edinburgh EH12 9SB, United Kingdom)'
df.loc[121,'point'] = '(55.934881, -3.334630)'
df.loc[121,'lat'] = 55.93488
df.loc[121,'lon'] = -3.33463
df.loc[121,'altitude'] = '0'
df.loc[214,'loc'] = '(49 Jamaica St, Liverpool L1 0AH, United Kingdom)'
df.loc[214,'point'] = '(53.395409, -2.980149)'
df.loc[214,'lat'] = 53.3954
df.loc[214,'lon'] = -2.98014
df.loc[214,'altitude'] = '0'
df.loc[326,'loc'] = '(1st Floor, 99 Clifton Street, London EC2A 4LG)'
df.loc[326,'point'] = '(51.522996, -0.083417)'
df.loc[326,'lat'] = 51.52299
df.loc[326,'lon'] = -0.08341
df.loc[326,'altitude'] = '0'
df.loc[395,'loc'] = '(25 Greenside Pl, Edinburgh EH1 3AA, United Kingdom)'
df.loc[395,'point'] = '(55.957294, -3.185021)'
df.loc[395,'lat'] = 55.95729
df.loc[395,'lon'] = -3.18502
df.loc[395,'altitude'] = '0'
df.loc[435,'loc'] = '(5th Floor, House, 52, 54 High Holborn, Holborn, London WC1V 6RL, United Kingdom)'
df.loc[435,'point'] = '(51.518419, -0.115012)'
df.loc[435,'lat'] = 51.51841
df.loc[435,'lon'] = -0.11501
df.loc[435,'altitude'] = '0'
df.loc[450,'loc'] = '(Screenworks Building, London N5 2EF, United Kingdom)'
df.loc[450,'point'] = '(51.550740, -0.097063)'
df.loc[450,'lat'] = 51.55074
df.loc[450,'lon'] = -0.09706
df.loc[450,'altitude'] = '0'
df.loc[480,'loc'] = '(5 Langley St, Covent Garden, London WC2H 9JA, United Kingdom)'
df.loc[480,'point'] = '(51.513187, -0.124933)'
df.loc[480,'lat'] = 51.51318
df.loc[480,'lon'] = -0.12493
df.loc[480,'altitude'] = '0'
df.loc[530,'loc'] = '(25 Wilton Road, Victoria, London, UK)'
df.loc[530,'point'] = '(51.495242, -0.142358)'
df.loc[530,'lat'] = 51.49524
df.loc[530,'lon'] = -0.14235
df.loc[530,'altitude'] = '0'

In [26]:
df.drop(columns=['altitude'])

,Ranking,Company name for communication,Country,Growth,Industry sector,loc,point,lat,lon
0,1,Revolut,UK,39754,Fintech,"(United Kingdom, (55.378051, -3.435973))","(55.378051, -3.435973, 0.0)",55.378051,-3.435973
1,2,OakNorth,UK,30706,Fintech,"(57 Broadwick St, Carnaby, London W1F 9QS, UK,...","(51.5130211, -0.1373418, 0.0)",51.513021,-0.137342
3,4,DivideBuy,UK,19572,Fintech,"(First Floor, Brunswick Court, Brunswick St, N...","(53.0123213, -2.220778, 0.0)",53.012321,-2.220778
11,12,Moteefe,UK,7394,Media and Entertainment,"(84 Eccleston Square, Pimlico, London SW1V 1NP...","(51.4931108, -0.1435609, 0.0)",51.493111,-0.143561
20,21,Clearmatics,UK,4900,Software,"(30 City Rd, London EC1Y 2AY, UK, (51.5226132,...","(51.5226132, -0.08738939999999999, 0.0)",51.522613,-0.087389
...,...,...,...,...,...,...,...,...,...
541,470,Cloudhouse,UK,183,Software,"(1 Ariel Way, London W12 7SL, UK, (51.5091304,...","(51.5091304, -0.2231225, 0.0)",51.509130,-0.223123
543,472,Zappi,UK,180,Software,"(The Enterprise Village, Prince Albert Gardens...","(53.5731559, -0.0772785, 0.0)",53.573156,-0.077278
565,490,disguise,UK,162,Software,"(United Kingdom, (55.378051, -3.435973))","(55.378051, -3.435973, 0.0)",55.378051,-3.435973
568,493,Purple WiFi,UK,161,Software,"(United Kingdom, (55.378051, -3.435973))","(55.378051, -3.435973, 0.0)",55.378051,-3.435973
575,500,Arcus Global,UK,157,Software,"(Future Business Centre, Kings Hedges Rd, Camb...","(52.234851, 0.129525, 0.0)",52.234851,0.129525

In [27]:
df.point.isna().sum()
df.dropna(subset=['point'], inplace=True)

### Geolocation of Netherlands Companies

In [28]:
#Set instructions to use Google API
base_url= "https://maps.googleapis.com/maps/api/geocode/json?"
AUTH_KEY = "AIzaSyAkvUUxfKc4Z5uMv58wOsd2usIdDHvxQTk"
geolocator = GoogleV3(api_key = AUTH_KEY)

components = [ ('country', 'NL' )]
def get_location(x):
    return geolocator.geocode(x, components=components)

df1["loc"] = df1["Company name for communication"].apply(get_location)
df1["point"]= df1["loc"].apply(lambda loc: tuple(loc.point) if loc else None)
df1[['lat', 'lon', 'altitude']] = pd.DataFrame(df1['point'].to_list(), index=df1.index)
df1.loc[211,'loc'] = '(Kruisstraat 5, 8501 BP Joure, Netherlands)'
df1.loc[211,'point'] = '(52.969678, 5.793303)'
df1.loc[211,'lat'] = 52.969678
df1.loc[211,'lon'] = 5.793303
df1.drop(columns=['altitude'])

,Ranking,Company name for communication,Country,Growth,Industry sector,loc,point,lat,lon
9,10,Flightgift / Hotelgift,NL,7628,Software,"(Herengracht 493, 1017 BT Amsterdam, Netherlan...","(52.365714, 4.8910971, 0.0)",52.365714,4.891097
16,17,Mews Systems,NL,5384,Software,"(Wibautstraat 137D, 1097 DN Amsterdam, Netherl...","(52.3495268, 4.917836599999999, 0.0)",52.349527,4.917837
21,22,PastBook,NL,4623,Media and Entertainment,"(A'dam Tower, Overhoeksplein 3, 1031 KS Amster...","(52.3839102, 4.902474, 0.0)",52.383910,4.902474
39,36,Simplicate,NL,3013,Software,"(Laan Corpus Den Hoorn 102-1, 9728 JR Groninge...","(53.1937232, 6.5536279, 0.0)",53.193723,6.553628
81,74,Channable,NL,1791,Software,"(Kromme Nieuwegracht 66, 3512 HL Utrecht, Neth...","(52.0906417, 5.125939700000001, 0.0)",52.090642,5.125940
...,...,...,...,...,...,...,...,...,...
532,461,FiscFree,NL,189,Software,"(Industrieweg 8, 8444 AS Heerenveen, Netherlan...","(52.9329834, 5.9481348, 0.0)",52.932983,5.948135
538,467,FindHotel,NL,185,Software,"(Nieuwe Looiersdwarsstraat 17, 1017 TZ Amsterd...","(52.360783, 4.893751, 0.0)",52.360783,4.893751
544,473,SpriteCloud,NL,177,Software,"(Generaal Vetterstraat 72b, 1059 BW Amsterdam,...","(52.343881, 4.846614, 0.0)",52.343881,4.846614
560,485,Intus Workforce Solutions,NL,167,Software,"(Princenhof Park 12, 3972 NG Driebergen-Rijsen...","(52.0658397, 5.2583797, 0.0)",52.065840,5.258380
567,492,Pimm Solutions,NL,162,Software,"(Westblaak 180, 3012 KN Rotterdam, Netherlands...","(51.9163212, 4.475754, 0.0)",51.916321,4.475754

In [29]:
df1.point.isna().sum()
df1.dropna(subset=['point'], inplace=True)

### Mapping Netherlands Companies by sector

In [30]:
## Now that we can see the map we can delete the outlier companies 
df1 = df1[df1['Company name for communication'] != 'Grizzly New Marketing']
df1 = df1[df1['Company name for communication'] != 'Cloud++']
df1 = df1[df1['Company name for communication'] != 'FiscFree']
df1 = df1[df1['Company name for communication'] != 'Stars and Stories']
x = list(zip(df1['lon'].values, df1['lat'].values))
## We can use the agglomerativeclustering to locate the claster easily
clustering = AgglomerativeClustering(7).fit(x)
clustering.labels_
df1['cluster'] = clustering.labels_
df1

,Ranking,Company name for communication,Country,Growth,Industry sector,loc,point,lat,lon,altitude,cluster
9,10,Flightgift / Hotelgift,NL,7628,Software,"(Herengracht 493, 1017 BT Amsterdam, Netherlan...","(52.365714, 4.8910971, 0.0)",52.365714,4.891097,0.0,3
16,17,Mews Systems,NL,5384,Software,"(Wibautstraat 137D, 1097 DN Amsterdam, Netherl...","(52.3495268, 4.917836599999999, 0.0)",52.349527,4.917837,0.0,3
21,22,PastBook,NL,4623,Media and Entertainment,"(A'dam Tower, Overhoeksplein 3, 1031 KS Amster...","(52.3839102, 4.902474, 0.0)",52.383910,4.902474,0.0,3
39,36,Simplicate,NL,3013,Software,"(Laan Corpus Den Hoorn 102-1, 9728 JR Groninge...","(53.1937232, 6.5536279, 0.0)",53.193723,6.553628,0.0,2
81,74,Channable,NL,1791,Software,"(Kromme Nieuwegracht 66, 3512 HL Utrecht, Neth...","(52.0906417, 5.125939700000001, 0.0)",52.090642,5.125940,0.0,0
104,93,Scrambled Group,NL,1458,Media and Entertainment,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
117,102,Appwiki,NL,1281,Media and Entertainment,"(Heresingel 4, B, 9711 ES Groningen, Netherlan...","(53.2138115, 6.5704626, 0.0)",53.213811,6.570463,0.0,2
122,107,3D Hubs,NL,1258,Software,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
126,111,Parkos,NL,1234,Software,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
134,119,POSTEX,NL,1164,Software,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
135,120,Team Nijhuis,NL,1156,Media and Entertainment,"(Prins Bernhardlaan 59, 7622 BE Borne, Netherl...","(52.30901, 6.741034000000001, 0.0)",52.309010,6.741034,0.0,6
139,124,APOC Aviation,NL,1088,Software,"(Industrieweg 48, 2651 BE Berkel en Rodenrijs,...","(51.9829849, 4.4566059, 0.0)",51.982985,4.456606,0.0,5
155,136,The Inner Circle,NL,963,Media and Entertainment,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
178,155,Zelfstroom,NL,895,Environmental Technology,"(Statenlaan 14, 5223 LA 's-Hertogenbosch, Neth...","(51.68984589999999, 5.2902558, 0.0)",51.689846,5.290256,0.0,1
187,164,SendCloud,NL,856,Environmental Technology,"(Stadhuisplein 10, 5611 EM Eindhoven, Netherla...","(51.4350475, 5.479492899999999, 0.0)",51.435048,5.479493,0.0,1
213,186,Studytube,NL,755,Software,"(Naritaweg 70, 1043 BZ Amsterdam, Netherlands,...","(52.3881878, 4.825226100000001, 0.0)",52.388188,4.825226,0.0,3
270,235,Mapiq,NL,597,Software,"(Oostsingel 209, 2612 HL Delft, Netherlands, (...","(52.0200648, 4.351446, 0.0)",52.020065,4.351446,0.0,5
272,237,SecureLink,NL,588,Software,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
273,238,Foleon,NL,581,Software,"(4th floor, Transformatorweg 38-72, 1014 AK Am...","(52.3923186, 4.848865000000001, 0.0)",52.392319,4.848865,0.0,3
274,239,JouwWeb,NL,578,Software,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
280,245,Speakap,NL,554,Software,"(Pedro de Medinalaan 5, 1086 XK Amsterdam, Net...","(52.3633593, 4.9783301, 0.0)",52.363359,4.978330,0.0,3
283,248,2Solar software,NL,549,Software,"(Zuiderzeelaan 17A, 8017 JV Zwolle, Netherland...","(52.5026079, 6.0825808, 0.0)",52.502608,6.082581,0.0,4
294,255,Scribbr,NL,532,Software,"(Singel 542, 1017 AZ Amsterdam, Netherlands, (...","(52.3666451, 4.8923966, 0.0)",52.366645,4.892397,0.0,3
305,266,MessageBird,NL,504,Software,"(Trompenburgstraat 2C, 1079 TX Amsterdam, Neth...","(52.3442332, 4.9116167, 0.0)",52.344233,4.911617,0.0,3
308,269,Robin Radar Systems,NL,493,Software,"(Laan van Waalhaven 355, 2497 GM Den Haag, Net...","(52.0415423, 4.3610118, 0.0)",52.041542,4.361012,0.0,5
327,284,Rentman,NL,459,Software,"(Drift 17, 3512 BR Utrecht, Netherlands, (52.0...","(52.0937913, 5.1233833, 0.0)",52.093791,5.123383,0.0,0
334,291,OBI4wan,NL,442,Software,"(Korte Hogendijk 2, 1506 MA Zaandam, Netherlan...","(52.436906, 4.815436, 0.0)",52.436906,4.815436,0.0,3
348,301,The Next Ad,NL,422,Media and Entertainment,"(Transformatorweg 88, 1014 AK Amsterdam, Nethe...","(52.3926183, 4.8479576, 0.0)",52.392618,4.847958,0.0,3
351,304,Yellowgrape,NL,415,Media and Entertainment,"(Herengracht 231, 1016 BG Amsterdam, Netherlan...","(52.3727001, 4.8874685, 0.0)",52.372700,4.887468,0.0,3
352,305,Roamler,NL,411,Software,"(NDSM-Plein 20, 1033 WC Amsterdam, Netherlands...","(52.4005369, 4.893499600000001, 0.0)",52.400537,4.893500,0.0,3
353,306,VanMoof,NL,411,Software,"(Mauritskade 55, 1092 AD Amsterdam, Netherland...","(52.3617287, 4.9177479, 0.0)",52.361729,4.917748,0.0,3
356,309,Annual Insight,NL,408,Software,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
364,317,Building Blocks,NL,391,Software,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
366,319,ROBINHQ.COM,NL,386,Software,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
370,323,Concapps,NL,374,Software,"(Veemarktkade 8, 5222 AE 's-Hertogenbosch, Net...","(51.7016028, 5.2862063, 0.0)",51.701603,5.286206,0.0,1
371,324,Plek,NL,374,Software,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
372,325,CustomConcepts,NL,364,Media and Entertainment,"(Gillis van Ledenberchstraat 74, 1052 VK Amste...","(52.3763143, 4.871489299999999, 0.0)",52.376314,4.871489,0.0,3
377,326,Relay42,NL,364,Software,"(Meeuwenlaan 100, 1021 JL Amsterdam, Netherlan...","(52.3856953, 4.9216761, 0.0)",52.385695,4.921676,0.0,3
386,335,HousingAnywhere,NL,346,Software,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
387,336,Firmhouse,NL,346,Software,"(Stationsplein 45, 3013 AK Rotterdam, Netherla...","(51.9232492, 4.4692082, 0.0)",51.923249,4.469208,0.0,5
391,340,Jalt,NL,339,Media and Entertainment,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
397,346,ViriCiti,NL,330,Environmental Technology,"(Kabelweg 57, 1014 BA Amsterdam, Netherlands, ...","(52.39479799999999, 4.846481, 0.0)",52.394798,4.846481,0.0,3
409,354,MediMapp,NL,320,Software,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
414,359,New York Media Group,NL,314,Media and Entertainment,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
415,360,Werk aan de Muur,NL,312,Software,"(Hendrik Figeeweg 3G, 6, 2031 BJ Haarlem, Neth...","(52.3882436, 4.651775, 0.0)",52.388244,4.651775,0.0,3
420,365,Gadero,NL,309,Software,"(Straatweg 5, 3621 BG Breukelen, Netherlands, ...","(52.15385509999999, 5.019955299999999, 0.0)",52.153855,5.019955,0.0,0
425,370,Mail to Pay,NL,298,Software,"(Van Coulsterweg 2, 2952 CB Alblasserdam, Neth...","(51.8464418, 4.6782728, 0.0)",51.846442,4.678273,0.0,5
426,371,24i Media,NL,298,Media and Entertainment,"(Transformatorweg 78, 1014 AK Amsterdam, Nethe...","(52.3927153, 4.848034, 0.0)",52.392715,4.848034,0.0,3
456,397,Helloprint,NL,259,Software,"(Schiedamse Vest 89, 3012 BG Rotterdam, Nether...","(51.9160421, 4.4795199, 0.0)",51.916042,4.479520,0.0,5
472,409,Meetingselect,NL,245,Software,"(De Witte Toren, Rijksweg 81 a, 1411 GE Naarde...","(52.3072349, 5.1305166, 0.0)",52.307235,5.130517,0.0,0
479,416,EDC Retail,NL,229,Media and Entertainment,"(Phoenixweg 6, 9641 KS Veendam, Netherlands, (...","(53.0971039, 6.887815799999999, 0.0)",53.097104,6.887816,0.0,2
481,418,Ecotap,NL,228,Environmental Technology,"(Netherlands, (52.132633, 5.291265999999999))","(52.132633, 5.291265999999999, 0.0)",52.132633,5.291266,0.0,0
505,438,ValidSign,NL,212,Software,"(Zutphenseweg 42, 7211 ED Eefde, Netherlands, ...","(52.1846466, 6.2112042, 0.0)",52.184647,6.211204,0.0,4
509,442,I-team Global,NL,205,Environmental Technology,"(Hoppenkuil 27B, 5626 DD Eindhoven, Netherland...","(51.480008, 5.421951, 0.0)",51.480008,5.421951,0.0,1
510,443,JAMwerkt.nl,NL,203,Software,"(Freddy van Riemsdijkweg 28, 5657 EE Eindhoven...","(51.4570735, 5.396912899999999, 0.0)",51.457073,5.396913,0.0,1
528,457,Creative ICT,NL,192,Media and Entertainment,"(M. H. Tromplaan 3, 7511 JJ Enschede, Netherla...","(52.220522, 6.889943, 0.0)",52.220522,6.889943,0.0,6
538,467,FindHotel,NL,185,Software,"(Nieuwe Looiersdwarsstraat 17, 1017 TZ Amsterd...","(52.360783, 4.893751, 0.0)",52.360783,4.893751,0.0,3
544,473,SpriteCloud,NL,177,Software,"(Generaal Vetterstraat 72b, 1059 BW Amsterdam,...","(52.343881, 4.846614, 0.0)",52.343881,4.846614,0.0,3
560,485,Intus Workforce Solutions,NL,167,Software,"(Princenhof Park 12, 3972 NG Driebergen-Rijsen...","(52.0658397, 5.2583797, 0.0)",52.065840,5.258380,0.0,0
567,492,Pimm Solutions,NL,162,Software,"(Westblaak 180, 3012 KN Rotterdam, Netherlands...","(51.9163212, 4.475754, 0.0)",51.916321,4.475754,0.0,5

In [31]:
# We find the centroid of the cluster located in amsterdam in this case
k_means = KMeans(init="k-means++", n_clusters=7, n_init=25)
k_means.fit(x)
k_means_labels = k_means.labels_
k_means_cluster_centers = k_means.cluster_centers_
k_means_cluster_centers
latitudea = 52.37593
longitudea = 4.86973752 
df1['cluster'].value_counts()

0    21
3    20
5     7
1     5
2     3
6     2
4     2
Name: cluster, dtype: int64

In [32]:
# Map for Netherlands
lat_nl = 52.132633 
long_nl =  5.291266
map_nl = folium.Map(location=[lat_nl, long_nl], zoom_start=7)

##colordict = {'Software': 'blue', 'Media and Entertainment': 'green', 'Environmental Technology': 'white'}
colordict = {0: 'blue', 1: 'green', 2: 'yellow', 3: 'red', 4: 'white', 5: 'orange', 6: 'grey'}

# add markers to map
for lat, lng, label, sector in zip(df1['lat'], df1['lon'], df1['Company name for communication'], df1['cluster']):
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label, 
        color='black',
        fill=True,
        fill_color=colordict[sector],
        fill_opacity=0.7,
        parse_html=False).add_to(map_nl)    
map_nl

### Mapping UK Companies by sector

In [33]:
## Now that we can see the map we can delete the outlier companies 
df = df[df['Company name for communication'] != 'DJS (UK) Limited']
df = df[df['Company name for communication'] != 'MPB Group Limited']
df = df[df['Company name for communication'] != 'Vizolution']
df = df[df['Company name for communication'] != 'Unify Communications Ltd.']
df = df[df['Company name for communication'] != 'Hutch']
df = df[df['Company name for communication'] != 'Person Centred Software']
df = df[df['Company name for communication'] != 'Peak']
df = df[df['Company name for communication'] != 'Bango']
df = df[df['Company name for communication'] != 'Giacom']
df = df[df['Company name for communication'] != 'SimplyCook']
df = df[df['Company name for communication'] != 'Cloudhouse']

In [34]:
x = list(zip(df['lon'].values, df['lat'].values))
clustering = AgglomerativeClustering(6).fit(x)
clustering.labels_
df['cluster'] = clustering.labels_
k_means = KMeans(init="k-means++", n_clusters=6, n_init=25)
k_means.fit(x)
k_means_labels = k_means.labels_
k_means_cluster_centers = k_means.cluster_centers_
k_means_cluster_centers
df['cluster'].value_counts()

4    33
1    29
2     6
0     5
5     4
3     3
Name: cluster, dtype: int64

In [35]:
# We get de coordinates of the cluster of London and Cambridge
k_means_cluster_centers = k_means.cluster_centers_
centroids = pd.DataFrame(k_means_cluster_centers)
latitude = 51.51470127
longitude = -0.10633714
latitudec = 52.23578662
longitudec = 0.1373794

In [36]:
lat_gb = 54.378051 
long_gb = -3.435973
map_gb = folium.Map(location=[lat_gb, long_gb], zoom_start=6)

colordict = {0: 'blue', 1: 'green', 2: 'yellow', 3: 'red', 4: 'white', 5: 'orange'}
###colordict = {'Software': 'blue', 'Media and Entertainment': 'green', 'Fintech': 'white', 'Hardware': 'red'}

with open('C:/Users/perez/london_boroughs.json') as json_data:
    london = json.load(json_data)
    
folium.GeoJson(
    london,
    name='geojson'
).add_to(map_gb)

# add markers to map
for lat, lng, label, sector in zip(df['lat'], df['lon'], df['Company name for communication'], df['cluster']):
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label, 
        color='black',
        fill=True,
        fill_color=colordict[sector],
        fill_opacity=0.7,
        parse_html=False).add_to(map_gb)    
map_gb

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/perez/london_boroughs.json'

### Foursquare API - UK

In [37]:
CLIENT_ID = 'UXH3QXWSKIKRCISLRKVKEGCO54GYL3RWVPU3FZ4HCBVDUOBN' # your Foursquare ID
CLIENT_SECRET = 'TSCQVX0CDVXZNLTEQW5X2LHUXQE53A2DRRJ22NJR54RKYHAY' # your Foursquare Secret
VERSION = '20180604'
LIMIT = 50
search_query = 'College & University' ##Nightlife Spot Outdoors & Recreation Shop & Service Travel & Transport Arts & Entertainment
radius = 2000
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
results = requests.get(url).json()

# assign relevant part of JSON to venues
venues = results['response']['venues']

In [38]:
CLIENT_ID = 'UXH3QXWSKIKRCISLRKVKEGCO54GYL3RWVPU3FZ4HCBVDUOBN' # your Foursquare ID
CLIENT_SECRET = 'TSCQVX0CDVXZNLTEQW5X2LHUXQE53A2DRRJ22NJR54RKYHAY' # your Foursquare Secret
VERSION = '20180604'
LIMIT = 30
search_query = 'College & University' ##Nightlife Spot Outdoors & Recreation Shop & Service Travel & Transport Arts & Entertainment
radius = 2000
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitudec, longitudec, VERSION, search_query, radius, LIMIT)
results = requests.get(url).json()

# assign relevant part of JSON to venues
venuesc = results['response']['venues']

In [39]:
# tranform venues into a dataframe
dataframe = pd.json_normalize(venues)
dataframe.head()

# keep only columns that include venue name, and anything that is associated with location
filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term
dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]
dataframe_filtered

,name,categories,address,lat,lng,labeledLatLngs,distance,postalCode,cc,city,state,country,formattedAddress,crossStreet,neighborhood,id
0,King's College London - Waterloo Campus,University,Stamford St,51.505598,-0.112166,"[{'label': 'display', 'lat': 51.50559751070975...",1090,SE1,GB,London,Greater London,United Kingdom,"[Stamford St, London, Greater London, SE1, Un...",NaN,NaN,4d2351912eb1f04d5c3e07c2
1,Royal College of Surgeons of England,Medical School,35-43 Lincoln's Inn Fields,51.515533,-0.115607,"[{'label': 'display', 'lat': 51.51553266542977...",648,WC2A 3PE,GB,Holborn,Greater London,United Kingdom,"[35-43 Lincoln's Inn Fields, Holborn, Greater ...",NaN,NaN,4c39e0173849c928c7ebc1b1
2,King's College London - Strand Campus,University,Strand,51.511627,-0.116376,"[{'label': 'display', 'lat': 51.5116270804117,...",775,WC2R 2LS,GB,London,Greater London,United Kingdom,"[Strand (at Surrey St), London, Greater London...",at Surrey St,NaN,4b72fb14f964a520ae932de3
3,University College London,University,Gower St,51.524395,-0.133593,"[{'label': 'display', 'lat': 51.52439526888408...",2174,WC1E 6BT,GB,London,Greater London,United Kingdom,"[Gower St (btwn Gower Pl. & Torrington Pl.), L...",btwn Gower Pl. & Torrington Pl.,NaN,4b0a52daf964a5203e2323e3
4,Royal College of Emergency Medicine,College Administrative Building,7-9 Bream's Buildings,51.516114,-0.111225,"[{'label': 'display', 'lat': 51.5161143873048,...",373,EC4A 1DT,GB,London,Greater London,United Kingdom,"[7-9 Bream's Buildings, London, Greater London...",NaN,NaN,4e32882a62e12985fd629203
5,Kings College Student Union,Student Center,Surrey St.,51.511180,-0.115169,"[{'label': 'display', 'lat': 51.51117983551853...",726,WC2R 2LS,GB,London,Greater London,United Kingdom,"[Surrey St., London, Greater London, WC2R 2LS,...",NaN,NaN,4bfd26f883bbd13a98ed62c5
6,King's College NHS Health Centre,Doctor's Office,Surrey Street,51.511238,-0.114956,"[{'label': 'display', 'lat': 51.51123788646011...",710,WC2R 2LS,GB,London,Greater London,United Kingdom,"[Surrey Street, London, Greater London, WC2R 2...",NaN,NaN,50d1aa74e4b0d3a90c1b4c83
7,King's College - Language Resource Center,College Arts Building,NaN,51.511255,-0.115696,"[{'label': 'display', 'lat': 51.511255, 'lng':...",753,NaN,GB,NaN,NaN,United Kingdom,[United Kingdom],NaN,NaN,56af76d438faae8405754445
8,Kensington College,College Administrative Building,"Wesley Ho, 4 Wild Court",51.515536,-0.119353,"[{'label': 'display', 'lat': 51.51553585857806...",906,WC2B 4AU,GB,London,Greater London,United Kingdom,"[Wesley Ho, 4 Wild Court, London, Greater Lond...",NaN,NaN,4d66271b84f28cfa13b36769
9,Royal College of Paediatrics and Child Health,Building,5-11 Theobalds Rd,51.520838,-0.115747,"[{'label': 'display', 'lat': 51.52083784902094...",944,WC1X 8SH,GB,London,Greater London,United Kingdom,"[5-11 Theobalds Rd, London, Greater London, WC...",NaN,NaN,5000242ae4b0978e430512ba
10,Royal College of Anaesthetists,College Academic Building,35 Red Lion Sq,51.519279,-0.119861,"[{'label': 'display', 'lat': 51.519278810924, ...",1066,WC1R 4SG,GB,London,Greater London,United Kingdom,"[35 Red Lion Sq, London, Greater London, WC1R ...",NaN,NaN,4bb09c27f964a520474f3ce3
11,Cats College,College Academic Building,43-45 Bloomsbury Sq.,51.518405,-0.121875,"[{'label': 'display', 'lat': 51.51840492661380...",1152,WC1A 2RA,GB,London,Greater London,United Kingdom,"[43-45 Bloomsbury Sq., London, Greater London,...",NaN,NaN,4e707015a8098087a01782f8
12,King's College London - Drury Lane Building,University,26-29 Drury Lane,51.514786,-0.123150,"[{'label': 'display', 'lat': 51.5147855725507,...",1164,WC2B 5RL,GB,London,Greater London,United Kingdom,"[26-29 Drury Lane (Strand Campus), London, Gre...",Strand Campus,NaN,4cd2a68625ee6dcbb034450f
13,"LonDEC, King's College London Dental Institute",Medical School,3rd Floor Franklin Wilkins Building,51.505456,-0.112899,"[{'label': 'display', 'lat': 51.50545575971391...",1125,SE1 9NH,GB,Waterloo,Greater London,United Kingdom,[3rd Floor Franklin Wilkins Building (150 Stam...,150 Stamford St,NaN,4d7b45026152b60c6c8f7b26
14,University College Hospital,Hospital,235 Euston Rd,51.525004,-0.136339,"[{'label': 'display', 'lat': 51.52500442254615...",2373,NW1 2BU,GB,Camden Town,Greater London,United Kingdom,"[235 Euston Rd (Gower St), Camden Town, Greate...",Gower St,NaN,4bfb839cab180f479befb3ce
15,Princes College,Office,36 New Oxford Street,51.517160,-0.125418,"[{'label': 'display', 'lat': 51.51715977380225...",1349,WC1A 1EP,GB,London,Greater London,United Kingdom,"[36 New Oxford Street, London, Greater London,...",NaN,NaN,4f0d6a8ee4b0e190ab6ac78c
16,Global London College,College Academic Building,36 New Oxford St,51.517237,-0.125606,"[{'label': 'display', 'lat': 51.51723656908332...",1364,WC1A 1EP,GB,London,Greater London,United Kingdom,"[36 New Oxford St, London, Greater London, WC1...",NaN,NaN,4f9566fbe4b0b65a8c872028
17,College Hall,College Residence Hall,Malet St.,51.522250,-0.131133,"[{'label': 'display', 'lat': 51.52224975605932...",1912,WC1E 7HZ,GB,Camden Town,Greater London,United Kingdom,"[Malet St., Camden Town, Greater London, WC1E ...",NaN,NaN,4c2af66057a9c9b6db3ff567
18,King's College London - Bush House,College Technology Building,NaN,51.512600,-0.116931,"[{'label': 'display', 'lat': 51.51260002394812...",770,NaN,GB,NaN,NaN,United Kingdom,[United Kingdom],NaN,NaN,56a64089498ee1e85dc5c194
19,Shakespearean College,General College & University,34 Bloomsbury,51.518298,-0.127844,"[{'label': 'display', 'lat': 51.51829804463054...",1542,NaN,GB,London,Greater London,United Kingdom,"[34 Bloomsbury, London, Greater London, United...",NaN,NaN,5211f5b011d2775a7df60538
20,Goodenough College,Student Center,Mecklenburgh Sq.,51.526110,-0.118912,"[{'label': 'display', 'lat': 51.52611049009676...",1540,WC1N 2AN,GB,London,Greater London,United Kingdom,"[Mecklenburgh Sq., London, Greater London, WC1...",NaN,NaN,4b3f1bfaf964a52012a425e3
21,London College of Communication,College Arts Building,"UAL, Elephant & Castle",51.494837,-0.101476,"[{'label': 'display', 'lat': 51.49483667136030...",2236,SE1 6SB,GB,London,Greater London,United Kingdom,"[UAL, Elephant & Castle, London, Greater Londo...",NaN,NaN,4b62a4e8f964a520bb4d2ae3
22,Eynsford Language College,General College & University,37-39,51.516189,-0.131796,"[{'label': 'display', 'lat': 51.51618893787597...",1771,NaN,GB,London,Greater London,United Kingdom,"[37-39 (Oxford St.), London, Greater London, U...",Oxford St.,NaN,516556b0e4b068ba321da8a1
23,College of Arms,Monument / Landmark,130 Queen Victoria Street,51.512007,-0.098475,"[{'label': 'display', 'lat': 51.51200696300692...",621,EC4V 4BT,GB,London,Greater London,United Kingdom,"[130 Queen Victoria Street, London, Greater Lo...",NaN,City of London,4ac518d0f964a520b5a620e3
24,Kaplan International College London,General College & University,Palace House,51.532738,-0.107333,"[{'label': 'display', 'lat': 51.53273828651154...",2009,SE1 9DE,GB,London,Greater London,United Kingdom,"[Palace House (3 Cathedral Street), London, Gr...",3 Cathedral Street,Bermondsey,4c32e68b213c2d7fbe1f365d
25,CCL (College of Central London),General College & University,NaN,51.527130,-0.086530,"[{'label': 'display', 'lat': 51.52712964078540...",1948,NaN,GB,Лондон,NaN,United Kingdom,"[Лондон, United Kingdom]",NaN,NaN,4ec4e9c18b812a2064cba79a
26,"MRC Laboartory for Molecular Cell Biology, Uni...",Medical Lab,Gower Street,51.524280,-0.131795,"[{'label': 'display', 'lat': 51.52427960215237...",2060,WC1E 6BT,GB,London,Greater London,United Kingdom,"[Gower Street, Camden, Greater London, WC1E 6B...",NaN,NaN,4d8d22e3b46488bfdafdc5a2
27,College Of Medicine - KSU,Medical School,NaN,51.512803,-0.100416,"[{'label': 'display', 'lat': 51.512803, 'lng':...",461,NaN,GB,NaN,NaN,United Kingdom,[United Kingdom],NaN,NaN,534a32bf498e8d936002f2c5
28,Gresham College,University,Barnard's Inn Hall,51.517685,-0.109794,"[{'label': 'display', 'lat': 51.5176848146853,...",409,EC1N 2HH,GB,London,Greater London,United Kingdom,[Barnard's Inn Hall (btwn Fetter Ln. and Furni...,btwn Fetter Ln. and Furnival St.,NaN,4c18df22fe5a76b033a60215
29,Williams College,College Academic Building,NaN,51.517145,-0.105095,"[{'label': 'display', 'lat': 51.51714465968388...",285,NaN,GB,London,Greater London,United Kingdom,"[London, Greater London, United Kingdom]",NaN,NaN,4e08b79ed4c03ae0b9d16f5b
30,King’s College London Bush House-South East Wing,General College & University,NaN,51.512860,-0.116581,"[{'label': 'display', 'lat': 51.51286, 'lng': ...",738,WC2B 4LL,GB,London,Greater London,United Kingdom,"[London, Greater London, WC2B 4LL, United King...",NaN,NaN,5b47553342d8c2002ce50052
31,King’s College London - Bush House North East ...,College Academic Building,Aldwych,51.513034,-0.116899,"[{'label': 'display', 'lat': 51.513034, 'lng':...",754,WC2B 4BG,GB,London,Greater London,United Kingdom,"[Aldwych, London, Greater London, WC2B 4BG, Un...",NaN,NaN,5a65e791da5ede79a3dd4241
32,London College of Online Learning Limited,Adult Education Center,"Kemp House, 152-160 City Road",51.513535,-0.112449,"[{'label': 'display', 'lat': 51.51353461974712...",442,EC1V 2NX,GB,London,Greater London,United Kingdom,"[Kemp House, 152-160 City Road (Kemp House, 15...","Kemp House, 152-160 City Road",NaN,619a5a2f52dcb37fe93c2f5a
33,College Of Emergency Medicine,Medical School,NaN,51.519280,-0.119321,"[{'label': 'display', 'lat': 51.5192804875453,...",1033,NaN,GB,NaN,NaN,United Kingdom,[United Kingdom],NaN,NaN,4cd7c38ea423a35dd74ce842
34,London College Of Contemporary Art,General College & University,NaN,51.518055,-0.110587,"[{'label': 'display', 'lat': 51.518055, 'lng':...",475,EC1N 2LL,GB,NaN,NaN,United Kingdom,"[EC1N 2LL, United Kingdom]",NaN,NaN,5dce75384725c60008380f35
35,"The College, 12 Southampton Row",College Academic Building,NaN,51.518927,-0.121084,"[{'label': 'display', 'lat': 51.518927, 'lng':...",1124,W C1B,GB,London,Greater London,United Kingdom,"[London, Greater London, W C1B, United Kingdom]",NaN,NaN,5be5c8fc67af3a0039b418bb
36,st patricks college holborn,College Academic Building,NaN,51.515123,-0.114950,"[{'label': 'display', 'lat': 51.51512322025362...",598,NaN,GB,NaN,NaN,United Kingdom,[United Kingdom],NaN,NaN,516e660ee4b042332ac4ad24
37,The College Arms,Pub,18 Store Street,51.519854,-0.131830,"[{'label': 'display', 'lat': 51.51985384114787...",1856,WC1E 7DH,GB,London,Greater London,United Kingdom,"[18 Store Street, London, Greater London, WC1E...",NaN,NaN,4b588581f964a520e75b28e3
38,King's College London - Virginia Woolf Building,College Academic Building,22 Kingsway,51.514260,-0.118053,"[{'label': 'display', 'lat': 51.51425994999053...",813,W C2B,GB,London,Greater London,United Kingdom,"[22 Kingsway, London, Greater London, W C2B, U...",NaN,NaN,522d91ae11d28ed950b94b2a
39,London College of Fashion,General College & University,High holborn,51.517990,-0.116276,"[{'label': 'display', 'lat': 51.5179900298046,...",779,NaN,GB,Camden Town,Greater London,United Kingdom,"[High holborn, Camden Town, Greater London, Un...",NaN,NaN,4c36fcae3849c92859dfbcb1
40,Centre For Telecommunications Research-king's ...,College Academic Building,NaN,51.511780,-0.115796,"[{'label': 'display', 'lat': 51.51178, 'lng': ...",731,NaN,GB,NaN,NaN,United Kingdom,[United Kingdom],NaN,NaN,4d7e1340ebc15481772bdba6
41,Goodenough College (LH),College Residence Hall,London House,51.524426,-0.117504,"[{'label': 'display', 'lat': 51.52442569277209...",1330,WC1N 2AB,GB,Bloomsbury,Greater London,United Kingdom,"[London House (Mecklenburgh Square), Bloomsbur...",Mecklenburgh Square,NaN,4c18d9c36a21c9b67495c997
42,S401 - Kings College London,College Technology Building,Strand,51.512446,-0.116207,"[{'label': 'display', 'lat': 51.512446, 'lng':...",728,WC2 R 1,GB,London,Greater London,United Kingdom,"[Strand, London, Greater London, WC2 R 1, Unit...",NaN,NaN,4bebe61c62c0c928669be2d4
43,College Green,Garden,Abingdon St,51.497900,-0.126122,"[{'label': 'display', 'lat': 51.4979000208282,...",2318,SW1 P 3,GB,London,Greater London,United Kingdom,"[Abingdon St, London, Greater London, SW1 P 3,...",NaN,NaN,4be99cf3415e20a1310be4bb
44,The Dickson Poon School of Law (King's College),College Academic Building,Somerset House East Wing,51.511446,-0.116799,"[{'label': 'display', 'lat': 51.51144573027518...",810,WC2R 2LS,GB,London,Greater London,United Kingdom,"[Somerset House East Wing, London, Greater Lon...",NaN,NaN,51af29d4498e531b0feaf90a
45,cafe direct @ kings college,Café,NaN,51.511284,-0.115904,"[{'label': 'display', 'lat': 51.5112837912044,...",764,NaN,GB,NaN,NaN,United Kingdom,[United Kingdom],NaN,NaN,5138babbe4b0e0ccc3762214
46,Library Royal College Surgeons,College Library,NaN,51.515533,-0.115607,"[{'label': 'display', 'lat': 51.51553266542977...",648,NaN,GB,NaN,NaN,United Kingdom,[United Kingdom],NaN,NaN,54ec8606498e2e9b20fd7e8f
47,King's College - Geography Department,College Science Building,The Strand,51.511693,-0.116130,"[{'label': 'display', 'lat': 51.51169341219328...",756,NaN,GB,London,Greater London,United Kingdom,"[The Strand, London, Greater London, United Ki...",NaN,NaN,4f18028ce4b04c15e6a3322c
48,King's College Law School,Law School,Strand Somerset House,51.511308,-0.117140,"[{'label': 'display', 'lat': 51.51130794610128...",838,NaN,GB,NaN,NaN,United Kingdom,"[Strand Somerset House, United Kingdom]",NaN,NaN,506ac436e4b07f06b10193ff
49,"Department of War Studies, King's College London",General College & University,"King's Building, Strand",51.511924,-0.116468,"[{'label': 'display', 'lat': 51.51192379403626...",766,NaN,GB,London,Greater London,United Kingdom,"[King's Building, Strand, London, Greater Lond...",NaN,NaN,557ee737498e191d3efcb187

In [40]:
# tranform venues into a dataframe
dataframe = pd.json_normalize(venuesc)
dataframe.head()

# keep only columns that include venue name, and anything that is associated with location
filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filteredc = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
dataframe_filteredc['categories'] = dataframe_filteredc.apply(get_category_type, axis=1)

# clean column names by keeping only last term
dataframe_filteredc.columns = [column.split('.')[-1] for column in dataframe_filteredc.columns]
dataframe_filteredc

,name,categories,address,lat,lng,labeledLatLngs,distance,cc,city,state,country,formattedAddress,postalCode,id
0,Cambridge Regional College (CRC),Trade School,Kings Hedges Road,52.235356,0.133982,"[{'label': 'display', 'lat': 52.23535619082742...",236,GB,Cambridge,Cambridgeshire,United Kingdom,"[Kings Hedges Road, Cambridge, Cambridgeshire,...",NaN,4c0fca61b93cc9b61cb155e0
1,Cambridge Regional College Sports Centre,Gym / Fitness Center,NaN,52.234847,0.135380,"[{'label': 'display', 'lat': 52.23484676090613...",171,GB,NaN,NaN,United Kingdom,[United Kingdom],NaN,4d93283f9213b1f72551c146
2,LRC @ Cambridge Regional College,College Library,NaN,52.235321,0.134482,"[{'label': 'display', 'lat': 52.235321484912, ...",204,GB,NaN,NaN,United Kingdom,[United Kingdom],NaN,506ac419e4b014fb398a5e12
3,College fields park,Park,NaN,52.225881,0.136987,"[{'label': 'display', 'lat': 52.22588075994904...",1103,GB,NaN,NaN,United Kingdom,[United Kingdom],NaN,4fc126cde4b0117b73825586
4,Bellerbys College Campus Library,Library,NaN,52.225874,0.129697,"[{'label': 'display', 'lat': 52.225874, 'lng':...",1221,GB,Cambridge,Cambridgeshire,United Kingdom,"[Cambridge, Cambridgeshire, United Kingdom]",NaN,4eb3f70ae5fa17fc861cf763
5,Impington Village College,General College & University,New Lane,52.247581,0.116579,"[{'label': 'display', 'lat': 52.24758057245346...",1932,GB,Impington,Cambridgeshire,United Kingdom,"[New Lane, Impington, Cambridgeshire, United K...",NaN,4bf55627cad2c928bee59c99
6,Chesterton Community College,Community College,79 Bateson Rd,52.217615,0.122328,"[{'label': 'display', 'lat': 52.21761492302305...",2268,GB,Cambridge,Cambridgeshire,United Kingdom,"[79 Bateson Rd, Cambridge, Cambridgeshire, CB4...",CB4 3YN,4e6e728e2271a8cac03aea5b
7,Christ's College Boathouse,Gym / Fitness Center,NaN,52.213687,0.125596,"[{'label': 'display', 'lat': 52.213687, 'lng':...",2587,GB,NaN,NaN,United Kingdom,[United Kingdom],NaN,514a13dae4b0a74cdde8bba4

In [41]:
venues_map = folium.Map(location=[latitude, longitude], zoom_start=13) # generate map centred around the centroid of the London cluster

# add a red circle marker to represent the London centroid
folium.features.CircleMarker(
    [latitude, longitude],
    radius=10,
    color='red',
    popup='London Centroid',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add the Colleges & Universities as blue circle markers
for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map

In [42]:
venues_map = folium.Map(location=[latitudec, longitudec], zoom_start=13) # generate map centred around the centroid of the Cambridge cluster

# add a red circle marker to represent the Cambridge centroid
folium.features.CircleMarker(
    [latitudec, longitudec],
    radius=10,
    color='green',
    popup='Cambridge Centroid',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add the Colleges & Universities as blue circle markers
for lat, lng, label in zip(dataframe_filteredc.lat, dataframe_filteredc.lng, dataframe_filteredc.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map

### Foursquare API - Netherlands

In [43]:
CLIENT_ID = 'UXH3QXWSKIKRCISLRKVKEGCO54GYL3RWVPU3FZ4HCBVDUOBN' # your Foursquare ID
CLIENT_SECRET = 'TSCQVX0CDVXZNLTEQW5X2LHUXQE53A2DRRJ22NJR54RKYHAY' # your Foursquare Secret
VERSION = '20180604'
LIMIT = 30
search_query = 'College & University' ##Nightlife Spot Outdoors & Recreation Shop & Service Travel & Transport Arts & Entertainment
radius = 2000
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitudea, longitudea, VERSION, search_query, radius, LIMIT)
results = requests.get(url).json()
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitudea, longitudea, VERSION, search_query, radius, LIMIT)
results = requests.get(url).json()
# assign relevant part of JSON to venues
venuesa = results['response']['venues']

In [44]:
# tranform venues into a dataframe
dataframe = pd.json_normalize(venuesa)
dataframe.head()

# keep only columns that include venue name, and anything that is associated with location
filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filteredn = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venuea.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
dataframe_filteredn['categories'] = dataframe_filteredn.apply(get_category_type, axis=1)

# clean column names by keeping only last term
dataframe_filteredn.columns = [column.split('.')[-1] for column in dataframe_filteredn.columns]
dataframe_filteredn

,name,categories,address,crossStreet,lat,lng,labeledLatLngs,distance,postalCode,cc,city,state,country,formattedAddress,id
0,College Viva La Vida,Fraternity House,Marnixstraat 229,Westerstraat,52.377743,4.878774,"[{'label': 'display', 'lat': 52.377743, 'lng':...",646,1015 WD,NL,Amsterdam,Noord-Holland,Nederland,"[Marnixstraat 229 (Westerstraat), 1015 WD Amst...",4d0f2a16b765224b593be332
1,ALTRA College Centrum,School,Konijnenstraat 7,Hazenstraat,52.371140,4.881770,"[{'label': 'display', 'lat': 52.3711399, 'lng'...",976,1016 SL,NL,Amsterdam,Noord-Holland,Nederland,"[Konijnenstraat 7 (Hazenstraat), 1016 SL Amste...",4d791e0371a68cfa16411186
2,College Koninklijk Zeemanshoop,Club House,Muntplein 10,NaN,52.366346,4.893132,"[{'label': 'display', 'lat': 52.36634615867874...",1914,NaN,NL,Amsterdam,Noord-Holland,Nederland,"[Muntplein 10, Amsterdam, Nederland]",5454b32f498ea36c77e07a52
3,College Frat Boys P,Fraternity House,marnixstraat 221,westerstraat,52.376181,4.878048,"[{'label': 'display', 'lat': 52.376181, 'lng':...",565,1015wd,NL,Amsterdam,Noord-Holland,Nederland,"[marnixstraat 221 (westerstraat), 1015wd Amste...",4d0f3adbe236548177a570ea
4,Marcanti College,Community College,Jan van Galenstraat 17,NaN,52.375232,4.865673,"[{'label': 'display', 'lat': 52.37523249608226...",286,NaN,NL,Amsterdam,Noord-Holland,Nederland,"[Jan van Galenstraat 17, Amsterdam, Nederland]",4ad9b0aaf964a5206d1a21e3
5,College Frat Boys,Fraternity House,marnixstraat 226,westerstraat,52.369146,4.876717,"[{'label': 'display', 'lat': 52.36914636209053...",891,1015wd,NL,Jordaan,Noord-Holland,Nederland,"[marnixstraat 226 (westerstraat), 1015wd Jorda...",4d0f2ac8d467236a4bafbc4a
6,Frat Boys College R,Fraternity House,marnixstraat 223,westerstraat,52.377719,4.878774,"[{'label': 'display', 'lat': 52.37771864999999...",645,1015wd,NL,Amsterdam,Noord-Holland,Nederland,"[marnixstraat 223 (westerstraat), 1015wd Amste...",4d0f2e65c3dc3704bcfd3074
7,Frat Boys College Q,Fraternity House,marnixstraat 225,westerstraat,52.378679,4.878568,"[{'label': 'display', 'lat': 52.37867855409016...",673,1015wd,NL,Jordaan,Noord-Holland,Nederland,"[marnixstraat 225 (westerstraat), 1015wd Jorda...",4d0f2b306331a093d05e4f94
8,College,University,NaN,NaN,52.385898,4.843427,"[{'label': 'display', 'lat': 52.385898, 'lng':...",2104,NaN,NL,NaN,NaN,Nederland,[Nederland],503db674e4b06abc4a39ee25
9,College-Club,Office,Oudebrugsteeg 9,NaN,52.373844,4.894876,"[{'label': 'display', 'lat': 52.37384380423829...",1724,1016 GX,NL,Amsterdam,Noord-Holland,Nederland,"[Oudebrugsteeg 9, 1016 GX Amsterdam, Nederland]",52460c932fc63e75960fac87
10,College Hotel,Music Venue,NaN,NaN,52.370220,4.895170,"[{'label': 'display', 'lat': 52.37022, 'lng': ...",1841,NaN,NL,Amsterdam,Noord-Holland,Nederland,"[Amsterdam, Nederland]",6189cfe6f642c66dcc514b0e
11,Luzac College Amsterdam,School,Passeerdersgracht 25,NaN,52.366739,4.880632,"[{'label': 'display', 'lat': 52.366739, 'lng':...",1262,1016 XG,NL,Amsterdam,Noord-Holland,Nederland,"[Passeerdersgracht 25, 1016 XG Amsterdam, Nede...",5dc29a3cc6ee7a00082d714e
12,Cannabis College,Marijuana Dispensary,Oudezijds Achterburgwal 124,NaN,52.372140,4.897534,"[{'label': 'display', 'lat': 52.37213973022122...",1935,1012 DT,NL,Amsterdam,1012,Nederland,"[Oudezijds Achterburgwal 124, 1012 DT Amsterda...",4c193bb59990d13acb327c17
13,Huygens College,High School,2e constantijn huygensstraat 31,NaN,52.364408,4.872481,"[{'label': 'display', 'lat': 52.3644075066318,...",1296,NaN,NL,Amsterdam,Noord-Holland,Nederland,"[2e constantijn huygensstraat 31, Amsterdam, N...",4c0baa66009a0f47a25febbf
14,Leidenhoven College,College Academic Building,Roemer Visscherstraat,NaN,52.361042,4.875969,"[{'label': 'display', 'lat': 52.361042, 'lng':...",1710,1054 EW,NL,Amsterdam,Noord-Holland,Nederland,"[Roemer Visscherstraat, 1054 EW Amsterdam, Ned...",5acf3db632b61d325c0fa405
15,Iedersland College,General College & University,NaN,NaN,52.370013,4.844079,"[{'label': 'display', 'lat': 52.370013, 'lng':...",1864,NaN,NL,NaN,NaN,Nederland,[Nederland],50ee712de4b01c4a89553c69
16,Flight Attendant College,Student Center,NaN,NaN,52.365182,4.892201,"[{'label': 'display', 'lat': 52.365182, 'lng':...",1939,NaN,NL,NaN,NaN,Nederland,[Nederland],4d5925881d6cf04d330134fe
17,Media College,College Arts Building,condensatorweg,NaN,52.389748,4.851019,"[{'label': 'display', 'lat': 52.38974757952646...",1995,NaN,NL,Amsterdam,Noord-Holland,Nederland,"[condensatorweg, Amsterdam, Nederland]",4dcd05ecd22deadedd2de2bd
18,Luzac College,None,Prinsengracht 927,NaN,52.362220,4.891351,"[{'label': 'display', 'lat': 52.3622204511767,...",2118,1017 KD,NL,Amsterdam,Noord-Holland,Nederland,"[Prinsengracht 927, 1017 KD Amsterdam, Nederland]",4b6a7cccf964a52098d62be3
19,Altra College,High School,Stadhouderskade 60,Frans Halsstraat,52.358540,4.888616,"[{'label': 'display', 'lat': 52.35854028997932...",2322,1072 AC,NL,Amsterdam,Noord-Holland,Nederland,"[Stadhouderskade 60 (Frans Halsstraat), 1072 A...",4babc386f964a5207ac73ae3
20,Ag bell college,High School,Zekeringstraat 45,NaN,52.395968,4.848865,"[{'label': 'display', 'lat': 52.39596835311292...",2643,NaN,NL,Amsterdam,Noord-Holland,Nederland,"[Zekeringstraat 45, Amsterdam, Nederland]",4e65bbe6aeb7360316510601
21,Orion college West,General College & University,Zekeringstraat,NaN,52.395957,4.848846,"[{'label': 'display', 'lat': 52.39595746539847...",2642,NaN,NL,Amsterdam,Noord-Holland,Nederland,"[Zekeringstraat, Amsterdam, Nederland]",4edc78cb722e1da304b6f176
22,Collegezaal F0.01,College Classroom,Kloverniersburgwal (OMHP),NaN,52.369303,4.896608,"[{'label': 'display', 'lat': 52.3693027607959,...",1969,NaN,NL,Amsterdam,Noord-Holland,Nederland,"[Kloverniersburgwal (OMHP), Amsterdam, Nederland]",4d468c6e0349224be9be0e4f
23,Mediacollege Amsterdam,General College & University,Contactweg 36,NaN,52.391117,4.856823,"[{'label': 'display', 'lat': 52.39111693242768...",1904,1014AN,NL,Amsterdam,Noord-Holland,Nederland,"[Contactweg 36, 1014AN Amsterdam, Nederland]",4b62c3f7f964a520c7512ae3

In [45]:
venues_map = folium.Map(location=[latitudea, longitudea], zoom_start=13) # generate map centred around the centroid of the Amsterdam cluster

# add a red circle marker to represent the Amsterdam centroid
folium.features.CircleMarker(
    [latitudea, longitudea],
    radius=10,
    color='red',
    popup='Amsterdam centroid',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add the Colleges & Universities as blue circle markers
for lat, lng, label in zip(dataframe_filteredn.lat, dataframe_filteredn.lng, dataframe_filteredn.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map

##  Analysis <a name="analysis"></a>

In [46]:
dataframe_filtered.drop(columns=['id', 'state', 'labeledLatLngs', 'postalCode', 'formattedAddress', 'address',
                                 'crossStreet', 'neighborhood', 'cc', 'lng', 'lat', 'city'])

,name,categories,distance,country
0,King's College London - Waterloo Campus,University,1090,United Kingdom
1,Royal College of Surgeons of England,Medical School,648,United Kingdom
2,King's College London - Strand Campus,University,775,United Kingdom
3,University College London,University,2174,United Kingdom
4,Royal College of Emergency Medicine,College Administrative Building,373,United Kingdom
5,Kings College Student Union,Student Center,726,United Kingdom
6,King's College NHS Health Centre,Doctor's Office,710,United Kingdom
7,King's College - Language Resource Center,College Arts Building,753,United Kingdom
8,Kensington College,College Administrative Building,906,United Kingdom
9,Royal College of Paediatrics and Child Health,Building,944,United Kingdom
10,Royal College of Anaesthetists,College Academic Building,1066,United Kingdom
11,Cats College,College Academic Building,1152,United Kingdom
12,King's College London - Drury Lane Building,University,1164,United Kingdom
13,"LonDEC, King's College London Dental Institute",Medical School,1125,United Kingdom
14,University College Hospital,Hospital,2373,United Kingdom
15,Princes College,Office,1349,United Kingdom
16,Global London College,College Academic Building,1364,United Kingdom
17,College Hall,College Residence Hall,1912,United Kingdom
18,King's College London - Bush House,College Technology Building,770,United Kingdom
19,Shakespearean College,General College & University,1542,United Kingdom
20,Goodenough College,Student Center,1540,United Kingdom
21,London College of Communication,College Arts Building,2236,United Kingdom
22,Eynsford Language College,General College & University,1771,United Kingdom
23,College of Arms,Monument / Landmark,621,United Kingdom
24,Kaplan International College London,General College & University,2009,United Kingdom
25,CCL (College of Central London),General College & University,1948,United Kingdom
26,"MRC Laboartory for Molecular Cell Biology, Uni...",Medical Lab,2060,United Kingdom
27,College Of Medicine - KSU,Medical School,461,United Kingdom
28,Gresham College,University,409,United Kingdom
29,Williams College,College Academic Building,285,United Kingdom
30,King’s College London Bush House-South East Wing,General College & University,738,United Kingdom
31,King’s College London - Bush House North East ...,College Academic Building,754,United Kingdom
32,London College of Online Learning Limited,Adult Education Center,442,United Kingdom
33,College Of Emergency Medicine,Medical School,1033,United Kingdom
34,London College Of Contemporary Art,General College & University,475,United Kingdom
35,"The College, 12 Southampton Row",College Academic Building,1124,United Kingdom
36,st patricks college holborn,College Academic Building,598,United Kingdom
37,The College Arms,Pub,1856,United Kingdom
38,King's College London - Virginia Woolf Building,College Academic Building,813,United Kingdom
39,London College of Fashion,General College & University,779,United Kingdom
40,Centre For Telecommunications Research-king's ...,College Academic Building,731,United Kingdom
41,Goodenough College (LH),College Residence Hall,1330,United Kingdom
42,S401 - Kings College London,College Technology Building,728,United Kingdom
43,College Green,Garden,2318,United Kingdom
44,The Dickson Poon School of Law (King's College),College Academic Building,810,United Kingdom
45,cafe direct @ kings college,Café,764,United Kingdom
46,Library Royal College Surgeons,College Library,648,United Kingdom
47,King's College - Geography Department,College Science Building,756,United Kingdom
48,King's College Law School,Law School,838,United Kingdom
49,"Department of War Studies, King's College London",General College & University,766,United Kingdom

In [47]:
dataframe_filteredc.drop(columns=['id', 'state', 'labeledLatLngs', 'postalCode', 'formattedAddress', 'address', 
                                  'cc', 'lng', 'lat', 'city'])

,name,categories,distance,country
0,Cambridge Regional College (CRC),Trade School,236,United Kingdom
1,Cambridge Regional College Sports Centre,Gym / Fitness Center,171,United Kingdom
2,LRC @ Cambridge Regional College,College Library,204,United Kingdom
3,College fields park,Park,1103,United Kingdom
4,Bellerbys College Campus Library,Library,1221,United Kingdom
5,Impington Village College,General College & University,1932,United Kingdom
6,Chesterton Community College,Community College,2268,United Kingdom
7,Christ's College Boathouse,Gym / Fitness Center,2587,United Kingdom

In [48]:
dataframe_filteredn.drop(columns=['id', 'state', 'labeledLatLngs', 'postalCode', 'formattedAddress', 'address',
                                 'crossStreet', 'cc', 'lng', 'lat', 'city'])

,name,categories,distance,country
0,College Viva La Vida,Fraternity House,646,Nederland
1,ALTRA College Centrum,School,976,Nederland
2,College Koninklijk Zeemanshoop,Club House,1914,Nederland
3,College Frat Boys P,Fraternity House,565,Nederland
4,Marcanti College,Community College,286,Nederland
5,College Frat Boys,Fraternity House,891,Nederland
6,Frat Boys College R,Fraternity House,645,Nederland
7,Frat Boys College Q,Fraternity House,673,Nederland
8,College,University,2104,Nederland
9,College-Club,Office,1724,Nederland
10,College Hotel,Music Venue,1841,Nederland
11,Luzac College Amsterdam,School,1262,Nederland
12,Cannabis College,Marijuana Dispensary,1935,Nederland
13,Huygens College,High School,1296,Nederland
14,Leidenhoven College,College Academic Building,1710,Nederland
15,Iedersland College,General College & University,1864,Nederland
16,Flight Attendant College,Student Center,1939,Nederland
17,Media College,College Arts Building,1995,Nederland
18,Luzac College,None,2118,Nederland
19,Altra College,High School,2322,Nederland
20,Ag bell college,High School,2643,Nederland
21,Orion college West,General College & University,2642,Nederland
22,Collegezaal F0.01,College Classroom,1969,Nederland
23,Mediacollege Amsterdam,General College & University,1904,Nederland

As we can see trough the multiple maps and now this dataframes, the number of college and univirsities ara significatively high per number of companies on the list, being aware that we have a radius of 2km. Not many places in Europe have around 40 or more venues related with those parameters within 2km. Visualize the data in this case is difficult due to the fact that the size of the DataFrames are different and even being easy to do so, we do not count with many more information as restaurant and others due to the limited number of calls that we can do with Foursquare API.

## Results <a name="results"></a>

After all the process done, we can determine visually a clear correlation between the location and the suceess of that companies. Trough the agglomerative clusters of GB, we can appreciate clearly the distribution and the nucleus of these. 
In Scotland the cluster is defined with Glasgow and Edinbourgh, in London is cristal clear the agglomeration, separatedly but with a similar distribution we have two clusters more, in Cambridge and Oxford respectively and then we have two clusters with a interesting composition. We can see with less agglomeration, the nucleus in Manchester but having companies in Liverpool too and last but not least we see a distribution following almost vertically the cities of Leeds, Sheffield, Nottingham, Derby and Birmingham. In the last cluster it would be really interesting check the communication facilites in the arounds because it seems to follow another sort of pattern than the other clusters with a relative proximity in the same cluster but clearly communicated by a central highway.

## Conclusion <a name="conclusion"></a>

In a exercice of self criticism I would say that I tried to extract conclusions of a subject that is for more experimented programers and data scientists, as I spend barely two month by now learning Python. The remarkable interest of this subject is anyway worth trying because many times we see a extremely close scope on our disciplines and we totally lose the perspective of the problems to solve. In this case, we can try hundreds of ways to determine why a company is succesful, checking their market cap, revenues and as much financial terms as you want, but seeing a relation in what we would not spend time thinking about as the location of this companies is sometimes awakening. It has been spending time researching for and interesting topic that I have discovered what it is the Economy of agglomerations and the benefits of this discipline.