# Segmenting and Clustering Neighborhoods in Toronto

In [66]:
import numpy as np
import sys
import seaborn as sns
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import matplotlib as mpl
import matplotlib.pyplot as plt
import csv
import pylab as pl
import urllib.parse
import folium
import json
import geojson
import requests
import wikipedia as wp
import matplotlib.cm as cm
import matplotlib.colors as colors

#### Some of the libraries will be used for next labs

In [67]:
from folium.folium import Map
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe
from sklearn.cluster import KMeans
from bs4 import BeautifulSoup

%matplotlib inline

##### Installing a wikipedia package to read the content directly from it, I have optimazed code
##### It seems that the combination of CP listed twice has benn joined automatically

In [68]:
#Get the html source
html = wp.page("List of postal codes of Canada: M").html().encode("UTF-8")
df = pd.read_html(html)[0]
df.to_csv('beautifulsoup_pandas.csv',header=0,index=False)
df = pd.DataFrame(data=df)
df = df.drop(df[df.Neighbourhood == 'Not assigned'].index)
df

,Postal Code,Borough,Neighbourhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
8,M9A,Etobicoke,"Islington Avenue, Humber Valley Village"
9,M1B,Scarborough,"Malvern, Rouge"
11,M3B,North York,Don Mills
12,M4B,East York,"Parkview Hill, Woodbine Gardens"
13,M5B,Downtown Toronto,"Garden District, Ryerson"
14,M6B,North York,Glencairn
17,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov..."
18,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
20,M3C,North York,Don Mills
21,M4C,East York,Woodbine Heights
22,M5C,Downtown Toronto,St. James Town
23,M6C,York,Humewood-Cedarvale
26,M9C,Etobicoke,"Eringate, Bloordale Gardens, Old Burnhamthorpe..."
27,M1E,Scarborough,"Guildwood, Morningside, West Hill"
30,M4E,East Toronto,The Beaches
31,M5E,Downtown Toronto,Berczy Park
32,M6E,York,Caledonia-Fairbanks
36,M1G,Scarborough,Woburn
39,M4G,East York,Leaside
40,M5G,Downtown Toronto,Central Bay Street
41,M6G,Downtown Toronto,Christie
45,M1H,Scarborough,Cedarbrae
46,M2H,North York,Hillcrest Village
47,M3H,North York,"Bathurst Manor, Wilson Heights, Downsview North"
48,M4H,East York,Thorncliffe Park
49,M5H,Downtown Toronto,"Richmond, Adelaide, King"
50,M6H,West Toronto,"Dufferin, Dovercourt Village"
54,M1J,Scarborough,Scarborough Village
55,M2J,North York,"Fairview, Henry Farm, Oriole"
56,M3J,North York,"Northwood Park, York University"
57,M4J,East York,"East Toronto, Broadview North (Old East York)"
58,M5J,Downtown Toronto,"Harbourfront East, Union Station, Toronto Islands"
59,M6J,West Toronto,"Little Portugal, Trinity"
63,M1K,Scarborough,"Kennedy Park, Ionview, East Birchmount Park"
64,M2K,North York,Bayview Village
65,M3K,North York,Downsview
66,M4K,East Toronto,"The Danforth West, Riverdale"
67,M5K,Downtown Toronto,"Toronto Dominion Centre, Design Exchange"
68,M6K,West Toronto,"Brockton, Parkdale Village, Exhibition Place"
72,M1L,Scarborough,"Golden Mile, Clairlea, Oakridge"
73,M2L,North York,"York Mills, Silver Hills"
74,M3L,North York,Downsview
75,M4L,East Toronto,"India Bazaar, The Beaches West"
76,M5L,Downtown Toronto,"Commerce Court, Victoria Hotel"
77,M6L,North York,"North Park, Maple Leaf Park, Upwood Park"
80,M9L,North York,Humber Summit
81,M1M,Scarborough,"Cliffside, Cliffcrest, Scarborough Village West"
82,M2M,North York,"Willowdale, Newtonbrook"
83,M3M,North York,Downsview
84,M4M,East Toronto,Studio District
85,M5M,North York,"Bedford Park, Lawrence Manor East"
86,M6M,York,"Del Ray, Mount Dennis, Keelsdale and Silverthorn"
89,M9M,North York,"Humberlea, Emery"
90,M1N,Scarborough,"Birch Cliff, Cliffside West"
91,M2N,North York,"Willowdale, Willowdale East"
92,M3N,North York,Downsview
93,M4N,Central Toronto,Lawrence Park
94,M5N,Central Toronto,Roselawn
95,M6N,York,"Runnymede, The Junction North"
98,M9N,York,Weston
99,M1P,Scarborough,"Dorset Park, Wexford Heights, Scarborough Town..."
100,M2P,North York,York Mills West
102,M4P,Central Toronto,Davisville North
103,M5P,Central Toronto,"Forest Hill North & West, Forest Hill Road Park"
104,M6P,West Toronto,"High Park, The Junction South"
107,M9P,Etobicoke,Westmount
108,M1R,Scarborough,"Wexford, Maryvale"
109,M2R,North York,"Willowdale, Willowdale West"
111,M4R,Central Toronto,"North Toronto West, Lawrence Park"
112,M5R,Central Toronto,"The Annex, North Midtown, Yorkville"
113,M6R,West Toronto,"Parkdale, Roncesvalles"
114,M7R,Mississauga,Canada Post Gateway Processing Centre
116,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ..."
117,M1S,Scarborough,Agincourt
120,M4S,Central Toronto,Davisville
121,M5S,Downtown Toronto,"University of Toronto, Harbord"
122,M6S,West Toronto,"Runnymede, Swansea"
126,M1T,Scarborough,"Clarks Corners, Tam O'Shanter, Sullivan"
129,M4T,Central Toronto,"Moore Park, Summerhill East"
130,M5T,Downtown Toronto,"Kensington Market, Chinatown, Grange Park"
135,M1V,Scarborough,"Milliken, Agincourt North, Steeles East, L'Amo..."
138,M4V,Central Toronto,"Summerhill West, Rathnelly, South Hill, Forest..."
139,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har..."
142,M8V,Etobicoke,"New Toronto, Mimico South, Humber Bay Shores"
143,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
144,M1W,Scarborough,"Steeles West, L'Amoreaux West"
147,M4W,Downtown Toronto,Rosedale
148,M5W,Downtown Toronto,Stn A PO Boxes
151,M8W,Etobicoke,"Alderwood, Long Branch"
152,M9W,Etobicoke,"Northwest, West Humber - Clairville"
153,M1X,Scarborough,Upper Rouge
156,M4X,Downtown Toronto,"St. James Town, Cabbagetown"
157,M5X,Downtown Toronto,"First Canadian Place, Underground city"
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [41]:
df.shape

(103, 3)

###### Here finish the first part of the lab

In [52]:
df1 = pd.read_csv('C:/Users/perez/Documents/Python/Python38-32/Geospatial_Coordinates.csv')
df2 = df.merge(df1, how = 'left')

,Postal Code,Borough,Neighbourhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
8,M9A,Etobicoke,"Islington Avenue, Humber Valley Village"
9,M1B,Scarborough,"Malvern, Rouge"
11,M3B,North York,Don Mills
12,M4B,East York,"Parkview Hill, Woodbine Gardens"
13,M5B,Downtown Toronto,"Garden District, Ryerson"
14,M6B,North York,Glencairn
17,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov..."
18,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
20,M3C,North York,Don Mills
21,M4C,East York,Woodbine Heights
22,M5C,Downtown Toronto,St. James Town
23,M6C,York,Humewood-Cedarvale
26,M9C,Etobicoke,"Eringate, Bloordale Gardens, Old Burnhamthorpe..."
27,M1E,Scarborough,"Guildwood, Morningside, West Hill"
30,M4E,East Toronto,The Beaches
31,M5E,Downtown Toronto,Berczy Park
32,M6E,York,Caledonia-Fairbanks
36,M1G,Scarborough,Woburn
39,M4G,East York,Leaside
40,M5G,Downtown Toronto,Central Bay Street
41,M6G,Downtown Toronto,Christie
45,M1H,Scarborough,Cedarbrae
46,M2H,North York,Hillcrest Village
47,M3H,North York,"Bathurst Manor, Wilson Heights, Downsview North"
48,M4H,East York,Thorncliffe Park
49,M5H,Downtown Toronto,"Richmond, Adelaide, King"
50,M6H,West Toronto,"Dufferin, Dovercourt Village"
54,M1J,Scarborough,Scarborough Village
55,M2J,North York,"Fairview, Henry Farm, Oriole"
56,M3J,North York,"Northwood Park, York University"
57,M4J,East York,"East Toronto, Broadview North (Old East York)"
58,M5J,Downtown Toronto,"Harbourfront East, Union Station, Toronto Islands"
59,M6J,West Toronto,"Little Portugal, Trinity"
63,M1K,Scarborough,"Kennedy Park, Ionview, East Birchmount Park"
64,M2K,North York,Bayview Village
65,M3K,North York,Downsview
66,M4K,East Toronto,"The Danforth West, Riverdale"
67,M5K,Downtown Toronto,"Toronto Dominion Centre, Design Exchange"
68,M6K,West Toronto,"Brockton, Parkdale Village, Exhibition Place"
72,M1L,Scarborough,"Golden Mile, Clairlea, Oakridge"
73,M2L,North York,"York Mills, Silver Hills"
74,M3L,North York,Downsview
75,M4L,East Toronto,"India Bazaar, The Beaches West"
76,M5L,Downtown Toronto,"Commerce Court, Victoria Hotel"
77,M6L,North York,"North Park, Maple Leaf Park, Upwood Park"
80,M9L,North York,Humber Summit
81,M1M,Scarborough,"Cliffside, Cliffcrest, Scarborough Village West"
82,M2M,North York,"Willowdale, Newtonbrook"
83,M3M,North York,Downsview
84,M4M,East Toronto,Studio District
85,M5M,North York,"Bedford Park, Lawrence Manor East"
86,M6M,York,"Del Ray, Mount Dennis, Keelsdale and Silverthorn"
89,M9M,North York,"Humberlea, Emery"
90,M1N,Scarborough,"Birch Cliff, Cliffside West"
91,M2N,North York,"Willowdale, Willowdale East"
92,M3N,North York,Downsview
93,M4N,Central Toronto,Lawrence Park
94,M5N,Central Toronto,Roselawn
95,M6N,York,"Runnymede, The Junction North"
98,M9N,York,Weston
99,M1P,Scarborough,"Dorset Park, Wexford Heights, Scarborough Town..."
100,M2P,North York,York Mills West
102,M4P,Central Toronto,Davisville North
103,M5P,Central Toronto,"Forest Hill North & West, Forest Hill Road Park"
104,M6P,West Toronto,"High Park, The Junction South"
107,M9P,Etobicoke,Westmount
108,M1R,Scarborough,"Wexford, Maryvale"
109,M2R,North York,"Willowdale, Willowdale West"
111,M4R,Central Toronto,"North Toronto West, Lawrence Park"
112,M5R,Central Toronto,"The Annex, North Midtown, Yorkville"
113,M6R,West Toronto,"Parkdale, Roncesvalles"
114,M7R,Mississauga,Canada Post Gateway Processing Centre
116,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ..."
117,M1S,Scarborough,Agincourt
120,M4S,Central Toronto,Davisville
121,M5S,Downtown Toronto,"University of Toronto, Harbord"
122,M6S,West Toronto,"Runnymede, Swansea"
126,M1T,Scarborough,"Clarks Corners, Tam O'Shanter, Sullivan"
129,M4T,Central Toronto,"Moore Park, Summerhill East"
130,M5T,Downtown Toronto,"Kensington Market, Chinatown, Grange Park"
135,M1V,Scarborough,"Milliken, Agincourt North, Steeles East, L'Amo..."
138,M4V,Central Toronto,"Summerhill West, Rathnelly, South Hill, Forest..."
139,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har..."
142,M8V,Etobicoke,"New Toronto, Mimico South, Humber Bay Shores"
143,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
144,M1W,Scarborough,"Steeles West, L'Amoreaux West"
147,M4W,Downtown Toronto,Rosedale
148,M5W,Downtown Toronto,Stn A PO Boxes
151,M8W,Etobicoke,"Alderwood, Long Branch"
152,M9W,Etobicoke,"Northwest, West Humber - Clairville"
153,M1X,Scarborough,Upper Rouge
156,M4X,Downtown Toronto,"St. James Town, Cabbagetown"
157,M5X,Downtown Toronto,"First Canadian Place, Underground city"
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

###### Here finish the second part of the lab

In [56]:
lat_toronto = 43.741667
long_toronto = -79.373333
map_toronto = folium.Map(location=[lat_toronto, long_toronto], zoom_start=10)

# add markers to map
for lat, lng, borough, neighborhood in zip(df2['Latitude'], df2['Longitude'], df2['Borough'], df2['Neighbourhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='darkblue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_toronto)  
    
map_toronto

In [65]:
df_toronto = df2[df2['Borough'].str.contains('Toronto')].reset_index(drop=True)

# create map of Manhattan using latitude and longitude values
map_borough = folium.Map(location=[lat_toronto, long_toronto], zoom_start=11)

# add markers to map
for lat, lng, label in zip(df_toronto['Latitude'], df_toronto['Longitude'], df_toronto['Neighbourhood']):
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_borough)  
    
map_borough